# FileView.php
# An easy to setup PHP script that allows you to display file directories for download and preview.
# https://github.com/Lovely-Experiences/FileView.php

# List of folder names which will never be displayed.
ignoredFolders:
  - fvcontents

# List of file names which will never be displayed.
ignoredFiles:
  - fvconfig.yaml

# List of file extensions which will never be displayed.
ignoredFileExtensions:
  - php

# Root directory to be displayed.
rootDirectory: ./

# Root URL which should be relevant to the directoryRoot.
rootURL: /

# If child folders should be displayed.
recursive: true
